version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: iac-localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration
      SERVICES: s3,ec2,iam,vpc,rds,cloudformation,lambda,apigateway,dynamodb,sns,sqs
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
      
      # AWS configuration for LocalStack
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      
      # Advanced LocalStack features
      PERSISTENCE: 1
      LAMBDA_EXECUTOR: docker-reuse
      
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    networks:
      - iac-network

networks:
  iac-network:
    driver: bridge

volumes:
  localstack-data:
    driver: local
