name: IaC Testing Framework - Simple CI/CD

# When to run this workflow
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-infrastructure:
    name: Test Infrastructure Code
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get the code
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Step 2: Setup Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    # Step 5: Start LocalStack for safe testing
    - name: Start LocalStack
      run: |
        docker-compose up -d localstack
        sleep 30  # Wait for LocalStack to be ready
    
    # Step 6: Run static analysis (quick and safe)
    - name: Run Static Analysis
      run: |
        python comprehensive_runner.py static ./static_analysis/examples
    
    # Step 7: Run policy compliance check
    - name: Run Policy Compliance
      run: |
        python comprehensive_runner.py policy ./static_analysis/examples
    
    # Step 8: Run comprehensive testing with LocalStack (safe)
    - name: Run Comprehensive Testing
      run: |
        python comprehensive_runner.py comprehensive ./static_analysis/examples --environment localstack --include-dynamic
    
    # Step 9: Upload results (optional)
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()  # Upload even if tests fail
      with:
        name: test-results
        path: |
          detailed_*.txt
          *.json
